
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pratik Tabhane
 */
public class InsertRecord extends javax.swing.JFrame {
    Connection con;
PreparedStatement pst;


    /**
     * Creates new form InsertRecord
     */
    public InsertRecord() {
         try {
        initComponents();
        setVisible(true);
         Class.forName("org.apache.derby.jdbc.ClientDriver");
        con=DriverManager.getConnection("jdbc:derby://localhost:1527/CitizenManagment","admin1","12345");
        JOptionPane.showMessageDialog(null,"DataBase Connected");
          pst=con.prepareStatement("insert into CITIZENINSERT values(?,?,?)");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(InsertRecord.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(InsertRecord.class.getName()).log(Level.SEVERE, null, ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adharid = new javax.swing.JTextField();
        lbluser = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        lbluser1 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        lbluser2 = new javax.swing.JLabel();
        clearrec = new javax.swing.JButton();
        Exitrec = new javax.swing.JButton();
        homerec = new javax.swing.JButton();
        insertrec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2021-09-24 114002.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Citizen Management");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2021-09-24 152936.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        adharid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharidActionPerformed(evt);
            }
        });

        lbluser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser.setText("Adhar ID");

        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });

        lbluser1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser1.setText("Full Name");

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        lbluser2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser2.setText("Address");

        clearrec.setBackground(new java.awt.Color(255, 153, 0));
        clearrec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clearrec.setText("Clear");
        clearrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearrecActionPerformed(evt);
            }
        });

        Exitrec.setBackground(new java.awt.Color(255, 153, 0));
        Exitrec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Exitrec.setText("Exit");
        Exitrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitrecActionPerformed(evt);
            }
        });

        homerec.setBackground(new java.awt.Color(255, 153, 0));
        homerec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        homerec.setText("Home");
        homerec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homerecActionPerformed(evt);
            }
        });

        insertrec.setBackground(new java.awt.Color(255, 153, 0));
        insertrec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        insertrec.setText("Insert");
        insertrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertrecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(adharid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbluser1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbluser2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(insertrec, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearrec, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Exitrec, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homerec)
                        .addGap(113, 113, 113)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adharid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbluser2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertrec)
                    .addComponent(clearrec)
                    .addComponent(Exitrec)
                    .addComponent(homerec))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adharidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adharidActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void clearrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearrecActionPerformed
        // TODO add your handling code here:
         adharid.setText(" ");
            fullname.setText(" ");
            address.setText(" ");
           adharid.requestFocus();


    }//GEN-LAST:event_clearrecActionPerformed

    private void ExitrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitrecActionPerformed
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_ExitrecActionPerformed

    private void homerecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homerecActionPerformed
        // TODO add your handling code here:
           setVisible(false);
            new MenuPage().setVisible(true);

    }//GEN-LAST:event_homerecActionPerformed

    private void insertrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertrecActionPerformed
        // TODO add your handling code here:
        String aid = adharid.getText();
        String fname = fullname.getText();
        String addr = address.getText();
        
        try
        {
            pst.setString(1,aid);
            pst.setString(2,fname);
            pst.setString(3,addr);
            
            int res=pst.executeUpdate();
            if(res>=1)
            {
                JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
                setVisible(false);
              MenuPage  h=new MenuPage();
                   h.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error Occurred");
            }
        }
        catch (HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(InsertRecord.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_insertrecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InsertRecord().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitrec;
    private javax.swing.JTextField address;
    private javax.swing.JTextField adharid;
    private javax.swing.JButton clearrec;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton homerec;
    private javax.swing.JButton insertrec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lbluser1;
    private javax.swing.JLabel lbluser2;
    // End of variables declaration//GEN-END:variables
}
