/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pratik Tabhane
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public MenuPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        filemenu = new javax.swing.JMenu();
        filelogin = new javax.swing.JMenuItem();
        filesignup = new javax.swing.JMenuItem();
        fileexit = new javax.swing.JMenuItem();
        menuedit = new javax.swing.JMenu();
        editinsert = new javax.swing.JMenuItem();
        editedit = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuhelp = new javax.swing.JMenu();
        menuabout = new javax.swing.JMenu();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filemenu.setText("File");

        filelogin.setText("Login");
        filelogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileloginActionPerformed(evt);
            }
        });
        filemenu.add(filelogin);

        filesignup.setText("Sign Up");
        filesignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filesignupActionPerformed(evt);
            }
        });
        filemenu.add(filesignup);

        fileexit.setText("Exit");
        fileexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileexitActionPerformed(evt);
            }
        });
        filemenu.add(fileexit);

        jMenuBar1.add(filemenu);

        menuedit.setText("Edit");

        editinsert.setText("Insert Record");
        editinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editinsertActionPerformed(evt);
            }
        });
        menuedit.add(editinsert);

        editedit.setText("Edit Record");
        menuedit.add(editedit);

        jMenuItem7.setText("Delete Record");
        menuedit.add(jMenuItem7);

        jMenuBar1.add(menuedit);

        menuhelp.setText("Help");
        jMenuBar1.add(menuhelp);

        menuabout.setText("About");
        jMenuBar1.add(menuabout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileexitActionPerformed

    private void fileloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileloginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new Login().setVisible(true);
    
    }//GEN-LAST:event_fileloginActionPerformed

    private void filesignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filesignupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new SignUp().setVisible(true);
    }//GEN-LAST:event_filesignupActionPerformed

    private void editinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editinsertActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new InsertRecord().setVisible(true);
    }//GEN-LAST:event_editinsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editedit;
    private javax.swing.JMenuItem editinsert;
    private javax.swing.JMenuItem fileexit;
    private javax.swing.JMenuItem filelogin;
    private javax.swing.JMenu filemenu;
    private javax.swing.JMenuItem filesignup;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menuabout;
    private javax.swing.JMenu menuedit;
    private javax.swing.JMenu menuhelp;
    // End of variables declaration//GEN-END:variables
}
