import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

 
public class Update extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst1,pst2,pst3,pst4;
    DefaultTableModel dtm;
    ResultSet rs;

    public Update() {
        try {
        initComponents();
        setVisible(true);
        Class.forName("org.apache.derby.jdbc.ClientDriver");
        con=DriverManager.getConnection("jdbc:derby://localhost:1527/CitizenManagment","admin1","12345");
        JOptionPane.showMessageDialog(null,"DataBase Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
    }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();
        adharid1 = new javax.swing.JTextField();
        lbluser = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        fullname1 = new javax.swing.JTextField();
        lbluser1 = new javax.swing.JLabel();
        lbluser4 = new javax.swing.JLabel();
        clearrec = new javax.swing.JButton();
        Exitrec = new javax.swing.JButton();
        homerec = new javax.swing.JButton();
        show = new javax.swing.JButton();
        upd = new javax.swing.JButton();
        dlt = new javax.swing.JButton();
        lbluser3 = new javax.swing.JLabel();
        lbluser5 = new javax.swing.JLabel();
        lbluser6 = new javax.swing.JLabel();
        religion1 = new javax.swing.JTextField();
        cast1 = new javax.swing.JTextField();
        contact1 = new javax.swing.JTextField();
        lbluser2 = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2021-09-24 114002.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Citizen Management");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2021-09-24 152936.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        stable.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "AdharId", "Name", "Gender", "Cast", "Religion", "Contact", "Address"
            }
        ));
        stable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stable);

        adharid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharid1ActionPerformed(evt);
            }
        });

        lbluser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser.setText("Adhar ID");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female ", "Other", " " }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        fullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullname1ActionPerformed(evt);
            }
        });

        lbluser1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser1.setText("Full Name");

        lbluser4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser4.setText("Gender");

        clearrec.setBackground(new java.awt.Color(255, 153, 0));
        clearrec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clearrec.setText("Clear");
        clearrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearrecActionPerformed(evt);
            }
        });

        Exitrec.setBackground(new java.awt.Color(255, 153, 0));
        Exitrec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Exitrec.setText("Exit");
        Exitrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitrecActionPerformed(evt);
            }
        });

        homerec.setBackground(new java.awt.Color(255, 153, 0));
        homerec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        homerec.setText("Home");
        homerec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homerecActionPerformed(evt);
            }
        });

        show.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        upd.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        upd.setText("Update");
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });

        dlt.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });

        lbluser3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser3.setText("Cast");

        lbluser5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser5.setText("Religion");

        lbluser6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser6.setText("Contact");

        religion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religion1ActionPerformed(evt);
            }
        });

        cast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cast1ActionPerformed(evt);
            }
        });

        contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact1ActionPerformed(evt);
            }
        });

        lbluser2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbluser2.setText("Address");

        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbluser1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbluser4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fullname1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(clearrec, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Exitrec, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(homerec))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbluser2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbluser3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbluser5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbluser6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(religion1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cast1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(upd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dlt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(adharid1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adharid1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cast1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(religion1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbluser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exitrec)
                    .addComponent(homerec)
                    .addComponent(clearrec))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adharid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adharid1ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void fullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullname1ActionPerformed

    private void clearrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearrecActionPerformed
        // TODO add your handling code here:
        adharid1.setText(" ");
        fullname1.setText(" ");
        cast1.setText(" ");
        religion1.setText(" ");
        contact1.setText(" ");
        address1.setText(" ");
        adharid1.requestFocus();
    }//GEN-LAST:event_clearrecActionPerformed

    private void ExitrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitrecActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitrecActionPerformed

    private void homerecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homerecActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MenuPage().setVisible(true);
    }//GEN-LAST:event_homerecActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
         int i=stable.getSelectedRow();
                
        try
        {
                int r;
                dtm=(DefaultTableModel)stable.getModel();
                r = Integer.parseInt(dtm.getValueAt(i,6).toString());
             //   System.out.println("r="+r);
                pst3=con.prepareStatement("delete from INSERT2 where ADHARID="+r+"");
                adharid1.setText(dtm.getValueAt(i,6).toString());
                fullname1.setText(dtm.getValueAt(i,0).toString().trim());
                cast1.setText(dtm.getValueAt(i,2).toString().trim());
                religion1.setText(dtm.getValueAt(i,3).toString().trim());
                contact1.setText(dtm.getValueAt(i,4).toString().trim());
                address1.setText(dtm.getValueAt(i,5).toString().trim());
               // System.out.println("id ="+id.getText()+ "    Name  "+name.getText()+"     Singer  "+singer.getText());
                int re=pst3.executeUpdate();
                if(re>=1)
                {
                    JOptionPane.showConfirmDialog(null,"Do You really want to DELETE?","Confirmation",JOptionPane.YES_NO_OPTION);
                    JOptionPane.showMessageDialog(null,"Item Deleted");
                    dtm.removeRow(i);
                    adharid1.setText("");
                    fullname1.setText("");
                    cast1.setText(" ");
                    religion1.setText(" ");
                    contact1.setText(" ");
                    address1.setText(" ");                   
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_dltActionPerformed

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed
        // TODO add your handling code here:
        int i=stable.getSelectedRow();
             
        try
        {   String gen = (String) gender.getSelectedItem();
            dtm=(DefaultTableModel)stable.getModel();
            int  r = Integer.parseInt(dtm.getValueAt(i,6).toString());
            pst1=con.prepareStatement("update INSERT2 set ADHARID=?, FULLNAME=?, GENDER=?, CAST1=?, RELIGION=?, CONTACT=?, ADDRESS=? where ADHARID="+r+"");
            pst1.setString(1,adharid1.getText());
            pst1.setString(2,fullname1.getText());
            pst1.setString(3,gen);
            pst1.setString(4,cast1.getText());
            pst1.setString(5,religion1.getText());
            pst1.setString(6,contact1.getText());
            pst1.setString(7,address1.getText());
            
            
            
            int r1=pst1.executeUpdate();
            if(r1>=1)
            {
                JOptionPane.showMessageDialog(this, "Updated Successfully");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            
            e.printStackTrace();
        }

           

    }//GEN-LAST:event_updActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
           try 
            {
                pst2=con.prepareStatement("select * from INSERT2",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                rs=pst2.executeQuery();
                ResultSetMetaData rsmd=rs.getMetaData();
                int cols=rsmd.getColumnCount();
                String colname[]=new String[cols];
                for(int i=1;i<=cols;i++)
                {
                    colname[i-1]=rsmd.getColumnName(i);
                }
                int rows=0;
                while(rs.next())
                {
                    rows++;
                }
                String data[][]=new String[rows][cols];
                rs.beforeFirst();
                rows=0;
                while(rs.next())
                {
                    for(int i=1;i<=cols;i++)
                    {
                        data[rows][i-1]=rs.getString(i);
                    }
                    rows++;
                    DefaultTableModel dtm = new DefaultTableModel(data,colname);
                    stable.setModel(dtm);
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

                                       

    }//GEN-LAST:event_showActionPerformed

    private void stableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stableMouseClicked
        // TODO add your handling code here:
         int i=stable.getSelectedRow();
        try
        {
            dtm=(DefaultTableModel)stable.getModel();
            pst4=con.prepareStatement("select * from INSERT2 where ADHARID=?");
            pst4.setString(1,adharid1.getText());
            adharid1.setText(dtm.getValueAt(i,6).toString());
            fullname1.setText(dtm.getValueAt(i,0).toString().trim());
            cast1.setText(dtm.getValueAt(i,2).toString().trim());
            religion1.setText(dtm.getValueAt(i,3).toString().trim());
            contact1.setText(dtm.getValueAt(i,4).toString().trim());
            address1.setText(dtm.getValueAt(i,5).toString().trim());
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_stableMouseClicked

    private void religion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religion1ActionPerformed

    private void cast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cast1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cast1ActionPerformed

    private void contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact1ActionPerformed

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitrec;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField adharid1;
    private javax.swing.JTextField cast1;
    private javax.swing.JButton clearrec;
    private javax.swing.JTextField contact1;
    private javax.swing.JButton dlt;
    private javax.swing.JTextField fullname1;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton homerec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lbluser1;
    private javax.swing.JLabel lbluser2;
    private javax.swing.JLabel lbluser3;
    private javax.swing.JLabel lbluser4;
    private javax.swing.JLabel lbluser5;
    private javax.swing.JLabel lbluser6;
    private javax.swing.JTextField religion1;
    private javax.swing.JButton show;
    private javax.swing.JTable stable;
    private javax.swing.JButton upd;
    // End of variables declaration//GEN-END:variables
}
